# Generated by Django 4.2.5 on 2023-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baserecord",
            name="test",
            field=models.CharField(default="test", max_length=10),
        ),
    ]
