# Generated by Django 4.2.5 on 2023-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(default="2008-01-01", null=True),
        ),
    ]
