# Generated by Django 4.2.5 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="full_keys",
        ),
        migrations.RemoveField(
            model_name="data",
            name="full_values",
        ),
        migrations.AddField(
            model_name="data",
            name="records",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="record",
            name="data_id",
            field=models.CharField(default="", max_length=65),
        ),
    ]
