# Generated by Django 4.2.5 on 2023-11-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(null=True),
        ),
    ]
