# Generated by Django 4.2.5 on 2023-11-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_baserecord_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baserecord",
            name="test",
        ),
    ]
