# Generated by Django 4.2.5 on 2023-11-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_family_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="token_expiration",
        ),
    ]
