# Generated by Django 4.2.5 on 2023-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_data_full_keys_remove_data_full_values_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(null=True),
        ),
    ]
