# Generated by Django 4.2.5 on 2023-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_family_token_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="token",
            field=models.CharField(default="000000", max_length=20),
        ),
        migrations.AddField(
            model_name="family",
            name="token_expiration",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
