# Generated by Django 4.2.5 on 2023-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_baserecord_child_family_remove_user_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='family',
            name='familyId',
            field=models.CharField(default='000000', max_length=20, unique=True),
        ),
    ]
