# Generated by Django 4.2.5 on 2023-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_baserecord_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="family",
            old_name="familyId",
            new_name="token",
        ),
        migrations.AddField(
            model_name="family",
            name="family_id",
            field=models.CharField(default="", max_length=10000, unique=True),
        ),
        migrations.AddField(
            model_name="family",
            name="token_expiration",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
