# Generated by Django 4.2.5 on 2023-10-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_family_name_remove_user_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "baserecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.baserecord",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.CharField(max_length=1024)),
                ("tags", models.CharField(max_length=200)),
            ],
            bases=("user.baserecord",),
        ),
        migrations.RemoveField(
            model_name="baserecord",
            name="type",
        ),
        migrations.AddField(
            model_name="baserecord",
            name="record_type",
            field=models.CharField(default="event", max_length=10),
        ),
    ]
