# Generated by Django 4.2.5 on 2023-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_event_remove_baserecord_type_baserecord_record_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.CharField(default="", max_length=65),
        ),
    ]
