# Generated by Django 4.2.5 on 2023-11-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_event_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "baserecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.baserecord",
                    ),
                ),
                ("title", models.CharField(max_length=128, null=True)),
                ("tags", models.CharField(max_length=128, null=True)),
            ],
            bases=("user.baserecord",),
        ),
        migrations.RemoveField(
            model_name="child",
            name="birthday",
        ),
        migrations.AddField(
            model_name="child",
            name="child_id",
            field=models.CharField(default="", max_length=65),
        ),
        migrations.AlterField(
            model_name="baserecord",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="baserecord",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=128, null=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("is_expired", models.BooleanField(default=False)),
                ("deadline", models.DateField(null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.plan"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="children",
            field=models.ManyToManyField(to="user.child"),
        ),
    ]
