# Generated by Django 4.2.5 on 2023-11-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_plan_remove_child_birthday_child_child_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "baserecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.baserecord",
                    ),
                ),
                ("keys", models.CharField(max_length=200)),
                ("values", models.CharField(max_length=200)),
                ("data_id", models.CharField(default="", max_length=65)),
            ],
            bases=("user.baserecord",),
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20)),
                ("value", models.FloatField()),
            ],
        ),
    ]
