# Generated by Django 4.2.5 on 2023-11-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0008_data_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baserecord",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="data",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="baserecord",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
