# Generated by Django 4.2.5 on 2023-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_baserecord_options_alter_data_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Record",
        ),
        migrations.AlterModelOptions(
            name="baserecord",
            options={},
        ),
        migrations.AlterModelOptions(
            name="data",
            options={},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={},
        ),
        migrations.RemoveField(
            model_name="baserecord",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="data",
            name="content",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="data",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="data",
            name="keys",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="data",
            name="values",
            field=models.CharField(max_length=128),
        ),
    ]
