# Generated by Django 4.2.5 on 2023-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_delete_record_alter_baserecord_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="content",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="data",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
