# Generated by Django 4.2.5 on 2023-11-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "baserecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.baserecord",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.CharField(max_length=1024)),
                ("tags", models.CharField(max_length=200)),
                ("text_id", models.CharField(default="", max_length=65)),
            ],
            bases=("user.baserecord",),
        ),
        migrations.RenameModel(
            old_name="Records",
            new_name="Record",
        ),
        migrations.RemoveField(
            model_name="data",
            name="keys",
        ),
        migrations.RemoveField(
            model_name="data",
            name="values",
        ),
    ]
