# Generated by Django 4.2.5 on 2023-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_text_rename_records_record_remove_data_keys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="value",
            field=models.FloatField(max_length=24),
        ),
    ]
